#spring.application.name=deparment-service

spring:
  application:
    name: deparment-service
  config:
    import: "optional:configserver:http://localhost:8088"

employee:
  service:
    url: http://localhost:8083/employee/department/
