#spring.application.name=deparment-service

spring:
  application:
    name: deparment-service

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
